server:
  port: 5000
spring:
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: SUBSCRIPTION-SERVICE
  #  sql:
  #    init:
  #      mode: always
  jpa:
    generate-ddl: true
    #    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:subscripdb
    #    username: root
    #    password: vedant
    driver-class-name: org.h2.Driver

